In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

1) How likely is it that you roll doubles when rolling two dice?

In [2]:
rng = np.random.default_rng(seed = 42)

In [3]:
doubles = rng.choice([ 1, 2, 3, 4, 5, 6], (1_000, 2))
doubles

array([[1, 5],
       [4, 3],
       [3, 6],
       ...,
       [5, 1],
       [4, 6],
       [2, 2]])

In [4]:
doubles[:,1]

array([5, 3, 6, 5, 1, 6, 5, 5, 1, 3, 3, 6, 4, 5, 3, 2, 4, 1, 5, 4, 5, 3,
       6, 6, 5, 2, 3, 1, 1, 5, 5, 6, 2, 3, 3, 2, 1, 3, 2, 5, 3, 5, 5, 2,
       5, 5, 3, 2, 5, 1, 2, 1, 5, 4, 5, 5, 3, 4, 1, 1, 5, 3, 4, 5, 4, 4,
       4, 2, 1, 3, 2, 3, 6, 2, 1, 2, 2, 4, 4, 5, 4, 3, 5, 2, 1, 1, 5, 3,
       1, 4, 1, 5, 3, 3, 2, 4, 3, 1, 1, 6, 6, 5, 2, 6, 5, 5, 3, 2, 1, 6,
       3, 2, 2, 4, 2, 6, 5, 5, 3, 4, 4, 4, 1, 3, 1, 3, 2, 1, 1, 4, 2, 6,
       4, 3, 4, 1, 6, 3, 5, 1, 3, 3, 6, 4, 3, 2, 2, 4, 3, 1, 5, 6, 1, 4,
       1, 5, 2, 4, 5, 5, 1, 6, 2, 1, 4, 3, 5, 5, 2, 6, 2, 4, 2, 6, 1, 1,
       3, 6, 6, 5, 6, 6, 4, 2, 5, 4, 3, 1, 5, 2, 6, 2, 1, 5, 1, 2, 4, 6,
       2, 2, 5, 6, 4, 1, 1, 2, 1, 5, 1, 4, 5, 4, 2, 5, 5, 5, 1, 1, 6, 3,
       2, 3, 4, 6, 2, 6, 1, 4, 4, 1, 1, 3, 6, 4, 6, 5, 3, 5, 1, 1, 5, 5,
       2, 4, 4, 6, 4, 3, 3, 3, 4, 6, 3, 2, 2, 5, 5, 1, 1, 4, 1, 5, 2, 1,
       6, 1, 2, 1, 1, 1, 1, 2, 1, 4, 5, 3, 2, 4, 6, 6, 1, 2, 2, 2, 4, 3,
       1, 3, 4, 1, 6, 1, 6, 1, 6, 6, 6, 5, 5, 4, 5,

In [5]:
(doubles[:,0] == doubles[:,1]).sum()

180

In [6]:
(doubles[:,0] == doubles[:,1]).sum() / len(doubles)

0.18

the likelyhood of rolling doubles when rolling two dice is 18%

2)

a)If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [7]:
#1 is heads, 0 is tails.
coin_flip = rng.choice([0,1], (1_000, 8))
coin_flip

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 1, 0],
       [0, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 0, 0],
       [1, 0, 1, ..., 0, 1, 1]])

In [8]:
coin_flip.sum(axis = 1)

array([2, 4, 5, 4, 5, 5, 4, 5, 5, 1, 5, 3, 5, 3, 7, 6, 4, 6, 3, 5, 5, 6,
       4, 2, 4, 2, 3, 2, 5, 4, 4, 4, 5, 3, 1, 6, 4, 3, 2, 3, 3, 4, 3, 5,
       2, 4, 3, 4, 5, 4, 5, 3, 3, 3, 4, 4, 4, 3, 2, 1, 2, 3, 5, 2, 6, 1,
       6, 3, 4, 4, 4, 5, 3, 2, 4, 6, 6, 5, 6, 4, 2, 6, 2, 5, 6, 3, 6, 3,
       3, 5, 4, 4, 3, 2, 6, 2, 4, 5, 3, 6, 3, 3, 6, 6, 5, 3, 1, 6, 2, 6,
       2, 3, 7, 4, 3, 3, 3, 6, 5, 3, 4, 5, 4, 6, 4, 6, 4, 3, 4, 3, 4, 4,
       1, 4, 4, 1, 3, 0, 5, 4, 6, 4, 2, 6, 6, 2, 6, 2, 5, 4, 6, 3, 4, 6,
       5, 5, 1, 3, 5, 4, 2, 1, 5, 2, 3, 3, 4, 5, 5, 4, 5, 4, 7, 5, 4, 4,
       3, 5, 5, 4, 4, 3, 4, 5, 5, 3, 5, 1, 5, 4, 2, 1, 5, 4, 3, 2, 6, 5,
       4, 4, 4, 6, 1, 6, 4, 7, 4, 5, 2, 5, 4, 3, 2, 5, 3, 6, 4, 4, 6, 4,
       5, 2, 4, 3, 3, 4, 3, 4, 5, 6, 4, 3, 3, 5, 4, 2, 5, 5, 6, 4, 5, 6,
       6, 2, 5, 5, 4, 5, 3, 4, 4, 2, 2, 3, 2, 2, 2, 5, 4, 5, 6, 5, 3, 2,
       1, 5, 6, 5, 3, 3, 3, 3, 3, 2, 4, 5, 5, 4, 3, 3, 1, 2, 2, 6, 5, 4,
       4, 2, 8, 3, 3, 4, 3, 4, 5, 4, 5, 3, 3, 3, 2,

In [9]:
(coin_flip.sum(axis = 1) == 3).sum() / len(coin_flip)

0.224

There is a 22.5% probability of getting exactly 3 heads.

b) What is the probability of getting more than 3 heads?

In [10]:
(coin_flip.sum(axis = 1) > 3).sum() / len(coin_flip)

0.618

There is an 84.3% probability of getting 3 or more heads.

3) There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 

Assuming that Codeup randomly selects an alumni to put on a billboard, 

what are the odds that the two billboards I drive past both have data science students on them?

In [11]:
cohorts = rng.choice([0, 0, 0, 1], (1_000, 2))
cohorts

array([[0, 0],
       [0, 0],
       [0, 1],
       ...,
       [1, 1],
       [0, 1],
       [0, 1]])

In [12]:
two_ds_bill = (cohorts.sum(axis = 1) == 2)

In [13]:
two_ds_bill.sum() / len(cohorts)

0.06

the odds that the two billboards I drive past both have data science students on them are 6%

4) Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine.

If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? 

(Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

1st try

In [37]:
avg_poptart = rng.normal(3, 1.5, 10_000)

In [38]:
#how many poptarts have been brought till friday afternoon
poptarts_till_fri_aft = (avg_poptart * 5)

In [39]:
((poptarts_till_fri_aft) < 17).sum()

6033

In [40]:
((poptarts_till_fri_aft) < 17).sum() / len(avg_poptart)

0.6033

2nd try

In [18]:
avg_poptart = rng.normal(3, 1.5, (1000,5))
avg_poptart

array([[5.31965084, 3.11446022, 2.5662534 , 3.72176113, 2.12143271],
       [3.22031276, 0.83629972, 4.63063078, 2.84338344, 4.73820129],
       [2.69829573, 2.79570044, 1.18152386, 4.13963546, 1.68624007],
       ...,
       [0.83427573, 3.40763078, 1.89407378, 4.79903521, 1.98071426],
       [1.64899353, 3.35043953, 1.97092971, 3.01282499, 4.478984  ],
       [3.175844  , 3.18144669, 3.30772006, 0.46035151, 3.58775662]])

In [19]:
pop_left__fri = (avg_poptart.sum(axis = 1) < 17).sum()

In [20]:
pop_left__fri / len(avg_poptart)

0.74

The likelyhood of being able to buy some poptarts on Friday afternoon is 74%

5) Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
 
Women have a mean of 170, sd = 6cm.

Since you have means and standard deviations, you can use np.random.normal to generate observations.

If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [21]:
men_heigths = rng.normal(178, 8, (1_000, 1))

In [22]:
women_heights = rng.normal(170, 6, (1_000, 1))

In [24]:
(women_heights > men_heigths).sum() /len(women_heights)

0.214

 The likelihood the woman is taller than the man is 21%

6) When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.

What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

50 students

In [25]:
fifty_students = rng.random((1000, 50))

In [26]:
(fifty_students > 1/250).prod(axis = 1).mean()

0.805

100 students

In [27]:
hundred_students = rng.random((1000, 100))

In [28]:
(hundred_students > 1/250).prod(axis = 1).mean()

0.669

150 students

In [29]:
hundred_fifty_students = rng.random((1000, 150))

In [50]:
1 - (hundred_fifty_students > 1/250).prod(axis = 1).mean()

0.45099999999999996

450 students

In [31]:
four_fifty_students = rng.random((1000, 450))

In [32]:
(four_fifty_students > 1/250).prod(axis = 1).mean()

0.169

7) There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 

a) However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [33]:
rng.random((1000, 3))

array([[0.19024919, 0.4252799 , 0.10633378],
       [0.03566494, 0.66453515, 0.76975895],
       [0.9199328 , 0.96948911, 0.23150409],
       ...,
       [0.68831324, 0.69798742, 0.42459487],
       [0.81010434, 0.36614362, 0.95975753],
       [0.3899219 , 0.68860115, 0.11571004]])

In [34]:
(rng.random((1000, 3)) > 70/100).prod(axis = 1).mean()

0.027

b) How likely is it that a food truck will show up sometime this week?

In [54]:
(rng.random((1000, 7)) <= 70/100).prod(axis = 1).mean()

0.088

8) If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [56]:
birthday_23 = pd.DataFrame(np.random.randint(0,365,(10_000,23)))
birthday_23.apply(lambda x: len(set(x)) != len(x),axis=1)
share_birthday_23 = birthday_23.apply(lambda x: len(set(x)) != len(x),axis=1).mean()
share_birthday_23

0.5118

In [57]:
birthday_20 = pd.DataFrame(np.random.randint(0,365,(10_000,20)))
birthday_20.apply(lambda x: len(set(x)) != len(x),axis=1)
share_birthday_20 = birthday_20.apply(lambda x: len(set(x)) != len(x),axis=1).mean()
share_birthday_20

0.4092

In [58]:
birthday_40 = pd.DataFrame(np.random.randint(0,365,(10_000,40)))
birthday_40.apply(lambda x: len(set(x)) != len(x),axis=1)
share_birthday_40 = birthday_40.apply(lambda x: len(set(x)) != len(x),axis=1).mean()
share_birthday_40

0.8914